ignore:
  - "libensemble/tools/parse_args.py"
  - "libensemble/tools/forkable_pdb.py"
  - "libensemble/tools/live_data/*"
  - "libensemble/sim_funcs/executor_hworld.py"
  - "libensemble/gen_funcs/persistent_tasmanian.py"
  - "libensemble/gen_classes/gpCAM.py"
