conda:
    file: conda/environment.yml
    environment: environment.yml

build:
    image: latest

python:
    version: 3.6
    pip_install: true
    setup_py_install: true
    install:
      - method: pip
      - sphinxcontrib.bibtex
      - sphinxcontrib-bibtex
      - requirements: docs/requirements.txt
    system_packages: true