[default]
extend-ignore-identifiers-re = [
    ".*NDArray.*",
    "8ba9de56.*"
]

[default.extend-words]
als = "als"
datas = "datas"
numer = "numer"
inout = "inout"
arange = "arange"
wrk = "wrk"
EOF = "EOF"
HPE = "HPE"
RO = "RO"
lst = "lst"
noy = "noy"

[files]
extend-exclude = ["*.bib", "*.xml", "docs/nitpicky"]
