[default]
extend-ignore-identifiers-re = [
    ".*NDArray.*",
    "8ba9de56.*"
]

[default.extend-words]
als = "als"
AAS = "AAS"
datas = "datas"
numer = "numer"
inout = "inout"

[files]
extend-exclude = ["*.bib", "*.xml", "docs/nitpicky"]
