name: libEnsemble
icon: https://raw.githubusercontent.com/Libensemble/libensemble/main/docs/images/libE_logo.png
headline: Tool for running dynamic ensembles.
description: |
  libEnsemble is a Python toolkit for running dynamic ensembles of calculations.

  Users write generator and simulator functions to express their ensembles.
  A library of example functions is available which can be modified as needed.
  These functions can submit unmodified external executables at any scale and
  in a portable way. System details are detected, and resource management is
  provided.

  libEnsemble can be used in a consistent manner on laptops, clusters, and
  supercomputers with minimal required dependencies.

language: Python

release:
  version: 1.2.0
  date: 2024-02-08

documentation:
  general: https://libensemble.readthedocs.io
  installation: https://libensemble.readthedocs.io/en/main/introduction.html#installation
  tutorial: https://libensemble.readthedocs.io/en/main/tutorials/local_sine_tutorial.html

execution_environment:
  interfaces:
    - Python API
  resource_managers:
    - Slurm
    - LSF
    - Cobalt
    - PBS
  transfer_protocols:
    - Globus
