#!/usr/bin/env python3

import argparse
import glob
import json
import os
import platform
import shutil
import subprocess
import sys
import time
from pathlib import Path

from rich.align import Align
from rich.console import Console
from rich.panel import Panel

# -----------------------------------------------------------------------------------------
# Configuration

# Using rich text output for formatting/color
RICH_OUTPUT = True

# Default options
RUN_UNIT_TESTS = True
RUN_REG_TESTS = True
COV_REPORT = True

# Regression test options
REG_TEST_LIST = "test_*.py"
REG_TEST_OUTPUT_EXT = "std.out"
REG_STOP_ON_FAILURE = False
REG_LIST_TESTS_ONLY = False  # just shows all tests to be run.
REG_RUN_LARGEST_TEST_ONLY = False

# Test Directories - all relative to project root dir
CODE_DIR = "libensemble"
LIBE_SRC_DIR = CODE_DIR
TESTING_DIR = Path(CODE_DIR) / "tests"
UNIT_TEST_SUBDIRS = [
    "unit_tests",
    "unit_tests_mpi_import",
    "unit_tests_nompi",
    "unit_tests_logger",
]
UNIT_TEST_DIRS = [TESTING_DIR / subdir for subdir in UNIT_TEST_SUBDIRS]
REG_TEST_SUBDIR = TESTING_DIR / "regression_tests"
FUNC_TEST_SUBDIR = TESTING_DIR / "functionality_tests"
REG_TEST_DIRS = [REG_TEST_SUBDIR, FUNC_TEST_SUBDIR]

# Coverage merge and report dir
COV_MERGE_DIR = TESTING_DIR

platform_mappings = {"Linux": "LIN", "Darwin": "OSX", "Windows": "WIN"}
cov_opts = ["-m", "coverage", "run", "--parallel-mode", "--concurrency=multiprocessing,thread"]
cov_report_type = "xml"  # e.g., html, xml

term_width = shutil.get_terminal_size().columns
if RICH_OUTPUT:
    term_width = max(term_width, 90)  # wide enough for most lines
    console = Console(force_terminal=True, width=term_width)
# -----------------------------------------------------------------------------------------
# Environment Variables

# Set environment variables as needed
os.environ["OMPI_SKIP_MPICXX"] = "1"
os.environ["OMP_NUM_THREADS"] = "1"

# -----------------------------------------------------------------------------------------
# Helper Functions


def find_project_root():
    """Find the project root directory."""
    root_dir = Path(__file__).resolve().parents[2]
    return str(root_dir)


def cprint(msg, newline=False, style=None, end="\n"):
    """Print line to console"""
    if RICH_OUTPUT:
        if newline:
            console.print()  # In console.print "\n" does not work in CI
        console.print(msg, style=style, end=end)
    else:
        if newline:
            print()
        print(msg, end=end)


def print_heading(heading, style="bold bright_magenta"):
    """Print a centered panel with the given heading and style."""
    if RICH_OUTPUT:
        panel = Panel(Align.center(heading), style=style, expand=True)
    else:
        panel = heading
    cprint(panel, newline=True)


def cleanup(root_dir):
    """Cleanup test run directories."""
    cprint("Cleaning any previous test output...", style="yellow")
    patterns = [
        ".cov_*",
        "cov_*",
        "ensemble_*",
        "workflow_*",
        "libE_history_at_abort_*.npy",
        "*.out",
        "*.err",
        "*.pickle",
        "simdir/*.x",
        "libe_task_*.out",
        "*libE_stats.txt",
        "my_machinefile",
        "libe_stat_files",
        "ensemble.log",
        "H_test.npy",
        "workflow_intermediate*",
        f"*.{REG_TEST_OUTPUT_EXT}",
        "*.npy",
        "*active_runs.txt",
        "outfile*.txt",
        "machinefile*",
        "my_simtask.x",
        "sim_*",
        "gen_*",
        "nodelist_*",
        "x_*.txt",
        "y_*.txt",
        "opt_*.txt_flag",
        "test_executor_forces_tutorial",
        "test_executor_forces_tutorial_2",
        # Coverage output generated by merge_coverage_reports
        "coverage.xml",
        # Cache files created by Ensemble/calling scripts
        ".libe_cache_*.meta.json",
        # Artifacts from forces build step
        "forces_app",
        "scaling_tests/forces/forces_app/forces.x",
        # Task output scripts in unit tests
        "libe_task_*.sh",
    ]
    dirs_to_clean = UNIT_TEST_DIRS + REG_TEST_DIRS
    for dir_path in dirs_to_clean:
        full_path = Path(root_dir) / dir_path
        full_path_str = str(full_path)
        if "libensemble/tests/" not in full_path_str.replace("\\", "/"):
            cprint(f"Safety check failed for {full_path_str}. Check directory", style="red")
            sys.exit(2)
        for pattern in patterns:
            for file_path in glob.glob(str(full_path / pattern)):
                try:
                    if os.path.isfile(file_path) or os.path.islink(file_path):
                        os.remove(file_path)
                    elif os.path.isdir(file_path):
                        shutil.rmtree(file_path)
                except Exception as e:
                    cprint(f"Error removing {file_path}: {e}", style="red")
    cprint("Cleanup completed.", style="green")


def total_time(start, end):
    """Return a time difference."""
    return round(end - start, 2)


def run_command(cmd, cwd=None, suppress_output=False):
    """Run a shell command and display its output."""
    # print(f"\nCommand: {' '.join(cmd)}\n")  # For debugging
    if suppress_output:
        with subprocess.Popen(cmd, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True) as proc:
            stdout, stderr = proc.communicate()
            if proc.returncode != 0:
                # SH: Print error output if fail (could show stdout also?)
                # print(stdout)
                print(stderr)
                raise subprocess.CalledProcessError(proc.returncode, cmd)
    else:
        subprocess.run(cmd, cwd=cwd, check=True)


def print_summary_line(phrase, style="cyan"):
    """Print a summary line with the specified style."""
    line = phrase.center(term_width, "=")
    cprint(f"{line}", newline=True, style=style)


def print_test_start(test_num, test_script_name, comm, nprocs):
    """Print the test start message."""
    cprint(
        f"---Test {test_num}: {test_script_name} starting with {comm} on {nprocs} processes ",
        style="cyan",
        newline=True,
    )


def print_test_passed(test_num, test_script_name, comm, nprocs, duration, suppress_output):
    """Print the test passed message."""
    if not suppress_output:
        cprint(f" ---Test {test_num}: {test_script_name} using {comm} on {nprocs} processes", end="")
    cprint(f"   ...passed after {duration} seconds", style="green")


def print_test_failed(test_num, test_script_name, comm, nprocs, duration):
    """Print the test failed message."""
    cprint(f" ---Test {test_num}: {test_script_name} using {comm} on {nprocs} processes", end="")
    cprint(f"   ...failed after {duration} seconds", style="red")


def merge_coverage_reports(root_dir):
    """Merge coverage data from multiple tests and generate a report."""
    print_heading("Generating coverage reports")
    tests_dir = Path(root_dir) / "libensemble" / "tests"
    cov_files = glob.glob(str(tests_dir / "**" / ".cov_*"), recursive=True)

    if cov_files:
        try:
            subprocess.run(["coverage", "combine"] + cov_files, cwd=tests_dir, check=True)
            subprocess.run(["coverage", cov_report_type], cwd=tests_dir, check=True)
            cprint("Coverage reports generated.", style="green")
        except subprocess.CalledProcessError as e:
            cprint("Error generating coverage reports.", style="red")
            sys.exit(e.returncode)
    else:
        cprint("No coverage files found to merge.", style="yellow")


def parse_bool(value):
    """Parse a boolean test directive value."""
    if value.lower() not in {"true", "false"}:
        raise ValueError(f"Expected true or false, got {value!r}")
    return value.lower() == "true"


def parse_test_directives(test_script, largest_nprocs_only=False):
    """Parse and validate test suite directives from a test script."""
    directives = {
        "comms": ["local"],
        "nprocs": [4],
        "extra": False,
        "exclude": False,
        "os_skip": [],
        "ompi_skip": False,
        "tier": "core",
        "features": [],
    }

    directive_patterns = [
        ("# TESTSUITE_COMMS:", "comms", lambda x: x.split()),
        ("# TESTSUITE_NPROCS:", "nprocs", lambda x: [int(n) for n in x.split()]),
        ("# TESTSUITE_EXTRA:", "extra", parse_bool),
        ("# TESTSUITE_EXCLUDE:", "exclude", parse_bool),
        ("# TESTSUITE_OS_SKIP:", "os_skip", lambda x: x.split()),
        ("# TESTSUITE_OMPI_SKIP:", "ompi_skip", parse_bool),
        ("# TESTSUITE_TIER:", "tier", str.lower),
        ("# TESTSUITE_FEATURES:", "features", lambda x: x.lower().split()),
    ]

    with open(test_script) as test_file:
        for line in test_file:
            for pattern, key, parse_func in directive_patterns:
                if line.startswith(pattern):
                    value = line.split(":", 1)[1].strip()
                    try:
                        directives[key] = parse_func(value)
                    except (TypeError, ValueError) as exc:
                        raise ValueError(f"Invalid {pattern[:-1]} in {test_script}: {exc}") from exc
                    break

    unknown_comms = set(directives["comms"]) - {"mpi", "local", "tcp", "threads"}
    if unknown_comms:
        raise ValueError(f"Unknown TESTSUITE_COMMS values in {test_script}: {sorted(unknown_comms)}")
    if not directives["nprocs"] or any(nprocs < 1 for nprocs in directives["nprocs"]):
        raise ValueError(f"TESTSUITE_NPROCS must contain positive integers in {test_script}")
    unknown_os = set(directives["os_skip"]) - set(platform_mappings.values())
    if unknown_os:
        raise ValueError(f"Unknown TESTSUITE_OS_SKIP values in {test_script}: {sorted(unknown_os)}")
    if directives["tier"] not in {"smoke", "core", "external", "slow"}:
        raise ValueError(f"Unknown TESTSUITE_TIER value in {test_script}: {directives['tier']}")
    if largest_nprocs_only or REG_RUN_LARGEST_TEST_ONLY:
        directives["nprocs"] = [directives["nprocs"][-1]]
    return directives


def is_open_mpi():
    """Check if Open MPI is being used."""
    try:
        result = subprocess.run(["mpiexec", "--version"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        if "Open MPI" in result.stdout or "OpenRTE" in result.stdout:
            return True
    except Exception:
        pass
    return False


def build_forces(root_dir):
    """Build forces.x using mpicc."""
    cprint("Building forces.x before running regression tests...", style="yellow", newline=True)
    forces_app_dir = Path(root_dir) / "libensemble/tests/scaling_tests/forces/forces_app"
    build_cmd = ["mpicc", "-O3", "-o", "forces.x", "forces.c", "-lm"]
    if platform.system() == "Darwin":
        build_cmd = ["mpicc", "-cc=clang", "-O3", "-o", "forces.x", "forces.c", "-lm"]
    subprocess.run(build_cmd, cwd=forces_app_dir, check=True)
    destination_dir = Path(root_dir) / "libensemble/tests/forces_app"
    os.makedirs(destination_dir, exist_ok=True)
    shutil.copy(forces_app_dir / "forces.x", destination_dir)


def skip_test(directives, args, current_os, test_script):
    """Return whether a script is excluded by metadata or CLI filters."""
    if directives["exclude"] or (directives["extra"] and not args.e):
        return True
    if current_os in directives["os_skip"]:
        return True
    if args.tier and directives["tier"] not in args.tier:
        return True
    if args.feature and not set(args.feature).issubset(directives["features"]):
        return True
    if args.match and not any(pattern in os.path.basename(test_script) for pattern in args.match):
        return True
    return False


def skip_config(directives, args, comm, open_mpi):
    """Skip a test configuration based on directives."""
    mpiexec_flags = args.a if args.a else ""
    if directives["ompi_skip"] and open_mpi and mpiexec_flags == "--oversubscribe" and comm == "mpi":
        return True
    return False


def make_run_line(python_exec, test_script, comm, nprocs, args):
    """Build a standalone test command."""
    cmd = python_exec + (cov_opts if args.coverage else []) + [test_script]
    if comm == "mpi":
        cmd = ["mpiexec", "-np", str(nprocs)] + (args.a.split() if args.a else []) + cmd
    else:
        cmd += ["--comms", comm, "--nworkers", str(nprocs - 1)]
    return cmd


def process_output(success, test_start, test_num, name, comm, nprocs, suppress):
    """Process output and return a timing record."""
    duration = total_time(test_start, time.time())
    if success:
        print_test_passed(test_num, name, comm, nprocs, duration, suppress)
    else:
        print_test_failed(test_num, name, comm, nprocs, duration)
    return {"test": name, "comms": comm, "nprocs": nprocs, "duration": duration, "passed": success}


def report_durations(records, count, output_path=None):
    """Print slow configurations and optionally write all timing records as JSON."""
    if records and count:
        print_heading(f"Slowest {min(count, len(records))} test configurations")
        for record in sorted(records, key=lambda item: item["duration"], reverse=True)[:count]:
            status = "passed" if record["passed"] else "failed"
            cprint(
                f"{record['duration']:8.2f}s  {record['test']} "
                f"({record['comms']}, {record['nprocs']} processes, {status})"
            )
    if output_path:
        with open(output_path, "w") as output_file:
            json.dump(records, output_file, indent=2)
            output_file.write("\n")


# -----------------------------------------------------------------------------------------
# Main Functions


def parse_arguments():
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description="LibEnsemble Test Runner")
    parser.add_argument("-c", "--clean", action="store_true", help="Clean up test directories and exit")
    parser.add_argument("-s", action="store_true", help="Print stdout and stderr during pytest (unit tests)")
    parser.add_argument("-z", action="store_true", help="Print stdout and stderr during regression tests")
    parser.add_argument("-u", action="store_true", help="Run only the unit tests")
    parser.add_argument("-r", action="store_true", help="Run only the regression tests")
    parser.add_argument("-m", action="store_true", help="Run the regression tests using MPI comms")
    parser.add_argument("-l", action="store_true", help="Run the regression tests using Local comms")
    parser.add_argument("-e", action="store_true", help="Run extra unit and regression tests")
    parser.add_argument("-A", metavar="<string>", help="Supply arguments to python")
    parser.add_argument("-a", metavar="<string>", help="Supply a string of args to add to mpiexec line")
    coverage_group = parser.add_mutually_exclusive_group()
    coverage_group.add_argument("--coverage", dest="coverage", action="store_true", help="Collect coverage")
    coverage_group.add_argument("--no-coverage", dest="coverage", action="store_false", help="Disable coverage")
    parser.set_defaults(coverage=COV_REPORT)
    parser.add_argument(
        "--list", action="store_true", help="List selected standalone test configurations without running"
    )
    parser.add_argument("--fail-fast", action="store_true", help="Stop after the first standalone test failure")
    parser.add_argument(
        "--largest-nprocs-only", action="store_true", help="Run only the largest TESTSUITE_NPROCS configuration"
    )
    parser.add_argument("--durations", type=int, default=0, metavar="N", help="Report the N slowest configurations")
    parser.add_argument("--timings-json", metavar="PATH", help="Write standalone test timings as JSON")
    parser.add_argument("--tier", action="append", choices=["smoke", "core", "external", "slow"])
    parser.add_argument("--feature", action="append", help="Require a TESTSUITE_FEATURES value")
    parser.add_argument("--match", action="append", help="Run standalone tests whose filename contains this value")
    args = parser.parse_args()
    if args.durations < 0:
        parser.error("--durations must be non-negative")
    return args


def run_unit_tests(root_dir, python_exec, args):
    """Run unit tests."""
    print_heading(f"Running unit tests (with pytest)")
    for dir_path in UNIT_TEST_DIRS:
        cprint(f"Entering unit test dir: {dir_path}", style="yellow", newline=True)
        full_path = Path(root_dir) / dir_path
        cmd = python_exec + ["-m", "pytest", "--color=yes", "--timeout=120"]
        if args.coverage:
            cov_rep = cov_report_type + ":cov_unit"
            cmd += ["--cov", "--cov-report", cov_rep]
        if args.durations:
            cmd.append(f"--durations={args.durations}")
        if args.e:
            cmd.append("--runextra")
        if args.s:
            cmd.append("--capture=no")
        run_command(cmd, cwd=full_path)


def run_regression_tests(root_dir, python_exec, args, current_os):
    """Run standalone regression and functionality tests."""
    list_only = REG_LIST_TESTS_ONLY or args.list
    user_comms_list = []
    if args.m:
        user_comms_list.append("mpi")
    if args.l:
        user_comms_list.append("local")
    if not user_comms_list:
        user_comms_list = ["mpi", "local"]

    print_heading(f"Running regression tests (comms: {', '.join(user_comms_list)})")

    reg_test_files = []
    for dir_path in REG_TEST_DIRS:
        full_path = Path(root_dir) / dir_path
        reg_test_files.extend(glob.glob(str(full_path / REG_TEST_LIST)))

    reg_test_files = sorted(reg_test_files)
    selected_test_files = []
    for test_script in reg_test_files:
        directives = parse_test_directives(test_script, args.largest_nprocs_only)
        if not skip_test(directives, args, current_os, test_script):
            selected_test_files.append(test_script)
    if not list_only and any("test_executor_forces_tutorial" in path for path in selected_test_files):
        build_forces(root_dir)

    open_mpi = is_open_mpi() if "mpi" in user_comms_list else False
    reg_pass = 0
    reg_fail = 0
    test_num = 0
    records = []
    start_time = time.time()

    for test_script in selected_test_files:
        test_script_name = os.path.basename(test_script)
        directives = parse_test_directives(test_script, args.largest_nprocs_only)
        comms_list = [comm for comm in directives["comms"] if comm in user_comms_list]
        for comm in comms_list:
            nprocs_list = directives["nprocs"]
            for nprocs in nprocs_list:
                if skip_config(directives, args, comm, open_mpi):
                    continue
                test_num += 1
                cmd = make_run_line(python_exec, test_script, comm, nprocs, args)
                cwd = os.path.dirname(test_script)
                print_test_start(test_num, test_script_name, comm, nprocs)
                if list_only:
                    continue
                test_start = time.time()
                try:
                    suppress_output = not args.z
                    run_command(cmd, cwd=cwd, suppress_output=suppress_output)
                    records.append(
                        process_output(True, test_start, test_num, test_script_name, comm, nprocs, suppress_output)
                    )
                    reg_pass += 1
                except subprocess.CalledProcessError as e:
                    records.append(
                        process_output(False, test_start, test_num, test_script_name, comm, nprocs, suppress_output)
                    )
                    reg_fail += 1
                    if args.fail_fast or REG_STOP_ON_FAILURE:
                        report_durations(records, args.durations, args.timings_json)
                        sys.exit(e.returncode)
    end_time = time.time()
    report_durations(records, args.durations, args.timings_json)
    total = reg_pass + reg_fail
    summary_style = "green" if reg_fail == 0 else "red"
    prefix = "FAIL" if reg_fail > 0 else "PASS"
    print_summary_line(
        f" {prefix}: {reg_pass}/{total} regression tests passed in {total_time(start_time, end_time)} seconds ",
        style=summary_style,
    )
    if reg_fail > 0:
        sys.exit(1)


def main():
    args = parse_arguments()
    root_dir = find_project_root()
    print_heading("************** libEnsemble Test-Suite **************", style="bold bright_yellow")

    cleanup(root_dir)  # Always clean up
    if args.clean:
        sys.exit(0)

    python_exec = ["python"]
    if args.A:
        python_exec += args.A.strip().split()

    global RUN_UNIT_TESTS, RUN_REG_TESTS
    TEST_OPTIONS = [args.u, args.r]
    if any(TEST_OPTIONS):
        RUN_UNIT_TESTS = args.u
        RUN_REG_TESTS = args.r

    base_os = platform.system()
    current_os = platform_mappings.get(base_os)

    # Any introductory info here
    cprint(f"Python executable/options: {' '.join(python_exec)}", style="white", newline=True)
    cprint(f"OS: {base_os} ({current_os})", style="white")

    if RUN_UNIT_TESTS:
        run_unit_tests(root_dir, python_exec, args)
    if RUN_REG_TESTS:
        run_regression_tests(root_dir, python_exec, args, current_os)
    if args.coverage:
        merge_coverage_reports(root_dir)

    # If you make this far, all passed.
    print_heading("***** All tests passed *****", style="green")


if __name__ == "__main__":
    main()
