name: libEnsemble-simple-CI

on:
  pull_request:
    types:
      - ready_for_review
      - opened
      - reopened
      - synchronize

jobs:
    test-libE:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                mpi-version: [mpich]
                python-version: [3.9, "3.10", "3.11", "3.12"]
                pydantic-version: ["2.6.4"]
                comms-type: [m, l]
                include:
                    - os: macos-latest
                      python-version: 3.11
                      mpi-version: mpich
                      pydantic-version: "2.6.4"
                      comms-type: m
                    - os: macos-latest
                      python-version: 3.11
                      mpi-version: mpich
                      pydantic-version: "2.6.4"
                      comms-type: l
                    - os: ubuntu-latest
                      python-version: "3.10"
                      mpi-version: mpich
                      pydantic-version: "2.6.4"
                      comms-type: t
                    - os: ubuntu-latest
                      mpi-version: "openmpi"
                      pydantic-version: "2.6.4"
                      python-version: "3.12"
                      comms-type: l
                    - os: ubuntu-latest
                      mpi-version: mpich
                      python-version: "3.10"
                      pydantic-version: "1.10.13"
                      comms-type: m
                    - os: ubuntu-latest
                      mpi-version: mpich
                      python-version: "3.10"
                      pydantic-version: "1.10.13"
                      comms-type: l

        env:
            HYDRA_LAUNCHER: "fork"
            TERM: xterm-256color
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        defaults:
            run:
                shell: bash -l {0}

        steps:
        - uses: actions/checkout@v4
        - name: Setup conda - Python ${{ matrix.python-version }}
          uses: conda-incubator/setup-miniconda@v3
          with:
            activate-environment: condaenv
            miniconda-version: "latest"
            python-version: ${{ matrix.python-version }}
            channels: conda-forge
            channel-priority: flexible
            auto-update-conda: true

        - name: Install basic testing/feature dependencies
          run: |
            pip install -r install/testing_requirements.txt
            pip install -r install/misc_feature_requirements.txt

        - name: Install generator dependencies
          run: |
            python -m pip install --upgrade pip
            pip install mpmath
            conda install numpy
            conda install scipy

        - name: Install libEnsemble, flake8, lock environment
          run: |
            pip install pydantic==${{ matrix.pydantic-version }}
            pip install -e .

        - name: Install generator dependencies for Ubuntu tests
          if: matrix.os == 'ubuntu-latest' && matrix.python-version != '3.12'
          run: |
            sudo apt-get install bc

        - name: Run extensive tests, Ubuntu
          if: matrix.os == 'ubuntu-latest'
          run: |
           ./libensemble/tests/run-tests.sh -e -s -u -z -${{ matrix.comms-type }}

    spellcheck:
        name: Spellcheck release branch
        if: contains(github.base_ref, 'develop')
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: crate-ci/typos@v1.23.2
