name: libEnsemble-simple-CI

on:
  pull_request:
    types:
      - ready_for_review
      - opened
      - reopened
      - synchronize

jobs:
    test-libE:
        if: '! github.event.pull_request.draft'
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                mpi-version: [mpich]
                python-version: ["py310", "py311", "py312", "py313"]
                pydantic-version: ["2.11.4"]
                comms-type: [m, l]
                include:
                    - os: macos-latest
                      python-version: "py311"
                      mpi-version: mpich
                      pydantic-version: "2.11.4"
                      comms-type: m
                    - os: macos-latest
                      python-version: "py311"
                      mpi-version: mpich
                      pydantic-version: "2.11.4"
                      comms-type: l
                    - os: ubuntu-latest
                      mpi-version: mpich
                      python-version: "py310"
                      pydantic-version: "1.10.22"
                      comms-type: m
                    - os: ubuntu-latest
                      mpi-version: mpich
                      python-version: "py310"
                      pydantic-version: "1.10.22"
                      comms-type: l

        env:
            HYDRA_LAUNCHER: "fork"
            TERM: xterm-256color
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        defaults:
            run:
                shell: bash -l {0}

        steps:
        - uses: actions/checkout@v4
          with:
            lfs: true

        - name: Checkout lockfile
          run: git lfs checkout

        - uses: prefix-dev/setup-pixi@v0.8.8
          with:
            pixi-version: v0.45.0
            # cache: true
            # frozen: true
            environments: ${{ matrix.python-version }}
            activate-environment: ${{ matrix.python-version }}

        - name: Install IBCDFO
          run: |
            pixi run -e ${{ matrix.python-version }} ./install/install_ibcdfo.sh

        - name: Install libEnsemble, test flake8
          run: |
            pip install pydantic==${{ matrix.pydantic-version }}
            pip install -e .
            flake8 libensemble

        - name: Remove various tests on newer pythons
          if: matrix.python-version == 'py311' || matrix.python-version == 'py312' || matrix.python-version == 'py313'
          run: |
            rm ./libensemble/tests/functionality_tests/test_local_sine_tutorial*.py # matplotlib errors on py312

        - name: Run simple tests, Ubuntu
          if: matrix.os == 'ubuntu-latest'
          run: |
           ./libensemble/tests/run_tests.py -A "-W error" -${{ matrix.comms-type }}

        - name: Run simple tests, macOS
          if: matrix.os == 'macos-latest'
          run: |
            pixi run -e ${{ matrix.python-version }} ./libensemble/tests/run_tests.py -A "-W error" -${{ matrix.comms-type }}

        - name: Merge coverage
          run: |
            mv libensemble/tests/.cov* .

        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v5
          env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    spellcheck:
        name: Spellcheck release branch
        if: contains(github.base_ref, 'develop')
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: crate-ci/typos@v1.32.0
