#!/bin/sh

# Job name to be reported by qstat
#PBS -N libE_run

# Declare Job, non-rerunable
#PBS -r n

# Specify name for output log file
#PBS -o log_libE_run

# Join standard output and error so we only get one logfile
#PBS -j oe

# Mail to user on a=abort, b=begin, e=end
#PBS -m aeb

# set the email address where job-related notifications will be sent
#PBS -M jmlarson@anl.gov

# Number of nodes 
##PBS -l nodes=2:ppn=32
#PBS -l nodes=4:ppn=16

# Specify CPU time needed
#PBS -l walltime=0:01:00

# Select queue 
##PBS -q haswell
##PBS -q biggpu
##PBS -q ivy
#PBS -q shared

export NLOPT_PYTHON_HOME="/home/jlarson/software/nlopt_install/lib/python2.7/site-packages"
export PYTHONPATH="${PYTHONPATH}:${NLOPT_PYTHON_HOME}"

cd $PBS_O_WORKDIR

# A little useful information for the log file...
echo Master process running on: $HOSTNAME
echo Directory is:  $PWD
echo PBS has allocated the following nodes:
cat $PBS_NODEFILE
NPROCS="$(wc -l < $PBS_NODEFILE)"
echo This job has allocated $NPROCS cores

rm libE_machinefile
# Uncomment the next two lines if you want 1 worker per node (and one node has a manager too)
head -n 1 $PBS_NODEFILE > libE_machinefile
cat $PBS_NODEFILE | sort | uniq >> libE_machinefile
#cat $PBS_NODEFILE | sort | uniq >> machinefile


# Put in a timestamp
echo Starting executation at: `date`

pwd
cmd="mpiexec -np 5 -machinefile libE_machinefile python2 call_libE_on_6-hump_camel_prasanna.py libE_machinefile"

echo The command is: $cmd
echo End PBS script information. 
echo All further output is from the process being run and not the pbs script.\n\n
$cmd

# Print the date again -- when finished
echo Finished at: `date`
